name: openwrt_cloud-build


on:
  schedule:
    - cron: '0 8 * * *'
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/hanwckf/immortalwrt-mt798x
  REPO_BRANCH: openwrt-21.02
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  CLASH_CORE: clash-core.sh
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  LAST_SHORT_HASH:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4 # Optimized to use a more specific version

    - name: 配置环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force -a
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL https://is.gd/depends_ubuntu_2204)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: 克隆源码
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        cd openwrt
        useVersionInfo=$(git show -s --date=short --format="Author: %an<br/>date: %cd<br/>commit: %s<br/>commit hash: %H<br/>")
        echo "useVersionInfo=$useVersionInfo" >> $GITHUB_ENV
        echo "LAST_SHORT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        
    - name: 检查是否编译
      id: checkNeed
      working-directory: /workdir
      run: |
        cd openwrt
        LATEST_RELEASE=`curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" --silent  "https://api.github.com/repos/wenpo1975/ea0326gmp/releases/latest" | jq -r .name`
        if [[ "$LATEST_RELEASE" == *"${{ env.LAST_SHORT_HASH }}"* ]]; then
          echo "already exists in the latest release, stopping compile..."
          echo "::set-output name=status::false"
        else
          echo "need compile for a new release..."
          echo "::set-output name=status::success"
        fi
          
    - name: 前置设置
      if: steps.checkNeed.outputs.status == 'success'
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: Update feeds
      if: steps.checkNeed.outputs.status == 'success'
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      if: steps.checkNeed.outputs.status == 'success'
      run: cd openwrt && ./scripts/feeds install -a

    - name: 后置设置
      if: steps.checkNeed.outputs.status == 'success'
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: clash core Download
      if: steps.checkNeed.outputs.status == 'success'
      run: |
        [ -e files ] && mv files openwrt/files
        cd openwrt
        chmod +x $GITHUB_WORKSPACE/$CLASH_CORE && $GITHUB_WORKSPACE/$CLASH_CORE
        
    - name: Download package
      if: steps.checkNeed.outputs.status == 'success'
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: 编译源码
      if: steps.checkNeed.outputs.status == 'success'
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: 显示磁盘状态
      if: steps.checkNeed.outputs.status == 'success' && (!cancelled())
      run: df -hT

    - name: Upload bin directory
      uses: actions/upload-artifact@v4 # Optimized to use a more specific version
      if: steps.checkNeed.outputs.status == 'success' && steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: openwrt/bin

    - name: Organize files
      id: organize
      if: steps.checkNeed.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        find . -type f ! -name '*.bin' -exec rm -f {} \;
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"
        echo "::set-output name=release_tag::$(date +"%Y-%m-%d %H%M")"

    - name: Calculate MD5 [计算MD5]
      if: steps.checkNeed.outputs.status == 'success'
      run: |
        cd ${{ env.FIRMWARE }} && rm -rf sha256sums
        MD5=$(md5sum * | awk '{ print $2 " " $1 }' | sed ':a;N;$!ba;s/\n/<br>/g')
        echo "MD5=$MD5" >> $GITHUB_ENV


    - name: Upload firmware directory
      uses: actions/upload-artifact@v4 # Optimized to use a more specific version
      if: steps.checkNeed.outputs.status == 'success' && steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}
        
    - name: 生成发布标签
      id: release_tag
      if: steps.checkNeed.outputs.status == 'success'
      run: |
        DATE_PREFIX=$(date +%y%m%d)
        echo "status=success" >> $GITHUB_OUTPUT
        echo "::set-output name=date_prefix::${DATE_PREFIX}"

    - name: Upload OpenWrt Firmware to Release
      id: release
      uses: ncipollo/release-action@main
      if: steps.checkNeed.outputs.status == 'success' && steps.organize.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        name: ${{ steps.organize.outputs.release_tag }}-${{ env.LAST_SHORT_HASH }}
        allowUpdates: true
        removeArtifacts: true
        tag: ${{ steps.release_tag.outputs.date_prefix }}-${{ env.LAST_SHORT_HASH }}
        commit: main
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ env.FIRMWARE }}/*
        body: |
          - 本项目是基于Hanwckf源代码编译的固件，**适用于H3C-NX30Pro设备**
          - 内置openclash、mosdns
          - 预置`geoip.dat` `Country.mmdb` 精简版只包含 `geoip:cn` 和 `geoip:private`
            预置`geosite.dat` `Loyalsoldier`自定义版，可代替官方 `geosite.dat`
            预置`geoip-asn.dat` 只包含新增类别，不包含 `CN`
          - 默认IP：192.168.10.1
          - 默认账号：root
          - 默认密码：(空)
          - 源码更新详情[点击这里查看](https://github.com/hanwckf/immortalwrt-mt798x/commits/openwrt-21.02/)
          - 升级更新选择sysupgrade.bin,出厂设置请刷factory.bin。
          - 升级前先下载备份，升级后还原备份后重新安装需要的插件即可。
          `md5信息`
          > ${{ env.MD5 }}


    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2 # Optimized to use a more specific version
      with:
        retain_days: 0
        keep_minimum_runs: 3
        
